version: 2

models:
  - name: trips_inc
    description: '{{ doc("trips_inc") }}'
    columns:
      - name: trip_id
        description: Unique identifier for each trip.
        data_type: INT
        tests:
          - not_null
          - unique
      - name: origin_city
        description: The city where the trip originated.
        data_type: VARCHAR
        tests:
          - not_null
      - name: destination_city
        description: The city where the trip ended.
        data_type: VARCHAR
        tests:
          - not_null

      - name: airplane_id
        description: The unique identifier for the airplane used in the trip.
        data_type: INT
        tests:
          - not_null
        
      - name: start_timestamp
        description: The timestamp when the trip started.
        data_type: TIMESTAMP
        tests:
          - not_null

      - name: end_timestamp
        description: The timestamp when the trip ended.
        data_type: TIMESTAMP
        tests:
          - not_null

      - name: load_date
        description: Ingestion date of the data
        data_type: DATE
        tests:
          - not_null
  - name: orders_inc
    description: '{{ doc("orders_inc") }}'
    columns:
      - name: order_id
        description: Unique identifier for each order.
        data_type: INT
        tests:
          - not_null
          - unique
      - name: customer_id
        description: The customer ID associated with the order.
        data_type: INT
        tests:
          - not_null
      - name: trip_id
        description: The trip ID associated with the order.
        data_type: INT
        tests:
          - not_null

      - name: price
        description: The amount charged for the order, in EUR.
        data_type: INT
        tests:
          - not_null
        
      - name: seat_no
        description: The seat number assigned to the order.
        data_type: VARCHAR
        tests:
          - not_null

      - name: status
        description: The status of the order (e.g., completed, pending).
        data_type: VARCHAR
        tests:
          - not_null

      - name: load_date
        description: Ingestion date of the data
        data_type: DATE
        tests:
          - not_null